// ------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン: 17.0.0.0
//  
//     このファイルへの変更は、正しくない動作の原因になる可能性があり、
//     コードが再生成されると失われます。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Kae.XTUML.Tools.Generator.DTDL.template
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class CommandDef : CommandDefBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            
            #line 6 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indent));
            
            #line default
            #line hidden
            this.Write("{\r\n");
            
            #line 7 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indent));
            
            #line default
            #line hidden
            
            #line 7 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indentDelta));
            
            #line default
            #line hidden
            this.Write("\"@type\": \"Command\",\r\n");
            
            #line 8 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indent));
            
            #line default
            #line hidden
            
            #line 8 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indentDelta));
            
            #line default
            #line hidden
            this.Write("\"name\": \"");
            
            #line 8 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(otfrDef.Attr_Name));
            
            #line default
            #line hidden
            this.Write("\",\r\n");
            
            #line 9 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"

	if (!string.IsNullOrEmpty(otfrDef.Attr_Descrip))
	{
        var tfrDescrip = DTDLGenerator.GetDescription(otfrDef, otfrDef.Attr_Descrip);

            
            #line default
            #line hidden
            
            #line 14 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indent));
            
            #line default
            #line hidden
            
            #line 14 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indentDelta));
            
            #line default
            #line hidden
            this.Write("\"description\": \"");
            
            #line 14 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tfrDescrip));
            
            #line default
            #line hidden
            this.Write("\",\r\n");
            
            #line 15 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"

	}

    var paramDefs = otfrDef.LinkedFromR117();
    if (paramDefs.Count() > 0)
    {

            
            #line default
            #line hidden
            
            #line 22 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indent));
            
            #line default
            #line hidden
            
            #line 22 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indentDelta));
            
            #line default
            #line hidden
            this.Write("\"request\": {\r\n");
            
            #line 23 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indent));
            
            #line default
            #line hidden
            
            #line 23 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indentDelta));
            
            #line default
            #line hidden
            
            #line 23 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indentDelta));
            
            #line default
            #line hidden
            this.Write("\"name\": \"payload\",\r\n");
            
            #line 24 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indent));
            
            #line default
            #line hidden
            
            #line 24 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indentDelta));
            
            #line default
            #line hidden
            
            #line 24 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indentDelta));
            
            #line default
            #line hidden
            this.Write("\"schema\": {\r\n");
            
            #line 25 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indent));
            
            #line default
            #line hidden
            
            #line 25 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indentDelta));
            
            #line default
            #line hidden
            
            #line 25 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indentDelta));
            
            #line default
            #line hidden
            
            #line 25 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indentDelta));
            
            #line default
            #line hidden
            this.Write("\"@type\": \"Object\",\r\n");
            
            #line 26 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indent));
            
            #line default
            #line hidden
            
            #line 26 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indentDelta));
            
            #line default
            #line hidden
            
            #line 26 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indentDelta));
            
            #line default
            #line hidden
            
            #line 26 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indentDelta));
            
            #line default
            #line hidden
            this.Write("\"fields\": [\r\n");
            
            #line 27 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"

        foreach(var paramDef in paramDefs)
        {
            var paramName = paramDef.Attr_Name;
            var sdtDef = paramDef.LinkedToR118();
            var schemaGen = new SchemaDef(indent + indentDelta + indentDelta + indentDelta + indentDelta + indentDelta, indentDelta, sdtDef);
            var schema = schemaGen.TransformText();

            
            #line default
            #line hidden
            
            #line 35 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indent));
            
            #line default
            #line hidden
            
            #line 35 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indentDelta));
            
            #line default
            #line hidden
            
            #line 35 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indentDelta));
            
            #line default
            #line hidden
            
            #line 35 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indentDelta));
            
            #line default
            #line hidden
            
            #line 35 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indentDelta));
            
            #line default
            #line hidden
            this.Write("{\r\n");
            
            #line 36 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indent));
            
            #line default
            #line hidden
            
            #line 36 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indentDelta));
            
            #line default
            #line hidden
            
            #line 36 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indentDelta));
            
            #line default
            #line hidden
            
            #line 36 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indentDelta));
            
            #line default
            #line hidden
            
            #line 36 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indentDelta));
            
            #line default
            #line hidden
            
            #line 36 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indentDelta));
            
            #line default
            #line hidden
            this.Write("\"name\": \"");
            
            #line 36 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(paramDef.Attr_Name));
            
            #line default
            #line hidden
            this.Write("\",\r\n");
            
            #line 37 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"

            if (!string.IsNullOrEmpty(paramDef.Attr_Descrip))
            {
                var descrip =  DTDLGenerator.GetDescription(paramDef, paramDef.Attr_Descrip);

            
            #line default
            #line hidden
            
            #line 42 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indent));
            
            #line default
            #line hidden
            
            #line 42 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indentDelta));
            
            #line default
            #line hidden
            
            #line 42 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indentDelta));
            
            #line default
            #line hidden
            
            #line 42 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indentDelta));
            
            #line default
            #line hidden
            
            #line 42 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indentDelta));
            
            #line default
            #line hidden
            
            #line 42 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indentDelta));
            
            #line default
            #line hidden
            this.Write("\"description\": \"");
            
            #line 42 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(descrip));
            
            #line default
            #line hidden
            this.Write("\",\r\n");
            
            #line 43 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"

            }

            
            #line default
            #line hidden
            
            #line 46 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(schema));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 47 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indent));
            
            #line default
            #line hidden
            
            #line 47 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indentDelta));
            
            #line default
            #line hidden
            
            #line 47 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indentDelta));
            
            #line default
            #line hidden
            
            #line 47 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indentDelta));
            
            #line default
            #line hidden
            
            #line 47 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indentDelta));
            
            #line default
            #line hidden
            this.Write("}\r\n");
            
            #line 48 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"

        }

            
            #line default
            #line hidden
            
            #line 51 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indent));
            
            #line default
            #line hidden
            
            #line 51 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indentDelta));
            
            #line default
            #line hidden
            
            #line 51 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indentDelta));
            
            #line default
            #line hidden
            
            #line 51 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indentDelta));
            
            #line default
            #line hidden
            this.Write("]\r\n");
            
            #line 52 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indent));
            
            #line default
            #line hidden
            
            #line 52 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indentDelta));
            
            #line default
            #line hidden
            
            #line 52 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indentDelta));
            
            #line default
            #line hidden
            this.Write("}\r\n");
            
            #line 53 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indent));
            
            #line default
            #line hidden
            
            #line 53 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indentDelta));
            
            #line default
            #line hidden
            this.Write("},\r\n");
            
            #line 54 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"

    }

    var returnDef = otfrDef.LinkedToR116();

            
            #line default
            #line hidden
            
            #line 59 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indent));
            
            #line default
            #line hidden
            
            #line 59 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indentDelta));
            
            #line default
            #line hidden
            this.Write("\"response\": {\r\n");
            
            #line 60 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"

    if (returnDef != null && returnDef.Attr_Name != "void")
    {
        var schemaGen = new SchemaDef(indent + indentDelta + indentDelta + indentDelta + indentDelta + indentDelta, indentDelta, returnDef);
        var schema = schemaGen.TransformText();

            
            #line default
            #line hidden
            
            #line 66 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indent));
            
            #line default
            #line hidden
            
            #line 66 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indentDelta));
            
            #line default
            #line hidden
            
            #line 66 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indentDelta));
            
            #line default
            #line hidden
            this.Write("\"name\": \"payload\",\r\n");
            
            #line 67 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indent));
            
            #line default
            #line hidden
            
            #line 67 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indentDelta));
            
            #line default
            #line hidden
            
            #line 67 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indentDelta));
            
            #line default
            #line hidden
            this.Write("\"schema\": {\r\n");
            
            #line 68 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indent));
            
            #line default
            #line hidden
            
            #line 68 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indentDelta));
            
            #line default
            #line hidden
            
            #line 68 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indentDelta));
            
            #line default
            #line hidden
            
            #line 68 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indentDelta));
            
            #line default
            #line hidden
            this.Write("\"@type\": \"Object\",\r\n");
            
            #line 69 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indent));
            
            #line default
            #line hidden
            
            #line 69 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indentDelta));
            
            #line default
            #line hidden
            
            #line 69 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indentDelta));
            
            #line default
            #line hidden
            
            #line 69 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indentDelta));
            
            #line default
            #line hidden
            this.Write("\"fields\": [\r\n");
            
            #line 70 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indent));
            
            #line default
            #line hidden
            
            #line 70 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indentDelta));
            
            #line default
            #line hidden
            
            #line 70 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indentDelta));
            
            #line default
            #line hidden
            
            #line 70 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indentDelta));
            
            #line default
            #line hidden
            
            #line 70 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indentDelta));
            
            #line default
            #line hidden
            this.Write("{\r\n");
            
            #line 71 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indent));
            
            #line default
            #line hidden
            
            #line 71 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indentDelta));
            
            #line default
            #line hidden
            
            #line 71 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indentDelta));
            
            #line default
            #line hidden
            
            #line 71 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indentDelta));
            
            #line default
            #line hidden
            
            #line 71 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indentDelta));
            
            #line default
            #line hidden
            
            #line 71 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indentDelta));
            
            #line default
            #line hidden
            this.Write("\"name\": \"result\",\r\n");
            
            #line 72 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(schema));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 73 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indent));
            
            #line default
            #line hidden
            
            #line 73 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indentDelta));
            
            #line default
            #line hidden
            
            #line 73 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indentDelta));
            
            #line default
            #line hidden
            
            #line 73 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indentDelta));
            
            #line default
            #line hidden
            
            #line 73 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indentDelta));
            
            #line default
            #line hidden
            this.Write("},\r\n");
            
            #line 74 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indent));
            
            #line default
            #line hidden
            
            #line 74 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indentDelta));
            
            #line default
            #line hidden
            
            #line 74 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indentDelta));
            
            #line default
            #line hidden
            
            #line 74 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indentDelta));
            
            #line default
            #line hidden
            
            #line 74 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indentDelta));
            
            #line default
            #line hidden
            this.Write("{\r\n");
            
            #line 75 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indent));
            
            #line default
            #line hidden
            
            #line 75 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indentDelta));
            
            #line default
            #line hidden
            
            #line 75 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indentDelta));
            
            #line default
            #line hidden
            
            #line 75 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indentDelta));
            
            #line default
            #line hidden
            
            #line 75 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indentDelta));
            
            #line default
            #line hidden
            
            #line 75 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indentDelta));
            
            #line default
            #line hidden
            this.Write("\"name\": \"status\",\r\n");
            
            #line 76 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indent));
            
            #line default
            #line hidden
            
            #line 76 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indentDelta));
            
            #line default
            #line hidden
            
            #line 76 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indentDelta));
            
            #line default
            #line hidden
            
            #line 76 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indentDelta));
            
            #line default
            #line hidden
            
            #line 76 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indentDelta));
            
            #line default
            #line hidden
            
            #line 76 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indentDelta));
            
            #line default
            #line hidden
            this.Write("\"schema\": \"integer\"\r\n");
            
            #line 77 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indent));
            
            #line default
            #line hidden
            
            #line 77 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indentDelta));
            
            #line default
            #line hidden
            
            #line 77 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indentDelta));
            
            #line default
            #line hidden
            
            #line 77 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indentDelta));
            
            #line default
            #line hidden
            
            #line 77 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indentDelta));
            
            #line default
            #line hidden
            this.Write("}\r\n");
            
            #line 78 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indent));
            
            #line default
            #line hidden
            
            #line 78 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indentDelta));
            
            #line default
            #line hidden
            
            #line 78 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indentDelta));
            
            #line default
            #line hidden
            
            #line 78 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indentDelta));
            
            #line default
            #line hidden
            this.Write("]\r\n");
            
            #line 79 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indent));
            
            #line default
            #line hidden
            
            #line 79 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indentDelta));
            
            #line default
            #line hidden
            
            #line 79 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indentDelta));
            
            #line default
            #line hidden
            this.Write("}\r\n");
            
            #line 80 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"

    }
    else
    {

            
            #line default
            #line hidden
            
            #line 85 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indent));
            
            #line default
            #line hidden
            
            #line 85 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indentDelta));
            
            #line default
            #line hidden
            
            #line 85 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indentDelta));
            
            #line default
            #line hidden
            this.Write("\"name\": \"status\",\r\n");
            
            #line 86 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indent));
            
            #line default
            #line hidden
            
            #line 86 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indentDelta));
            
            #line default
            #line hidden
            
            #line 86 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indentDelta));
            
            #line default
            #line hidden
            this.Write("\"schema\": \"integer\",\r\n");
            
            #line 87 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indent));
            
            #line default
            #line hidden
            
            #line 87 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indentDelta));
            
            #line default
            #line hidden
            
            #line 87 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indentDelta));
            
            #line default
            #line hidden
            this.Write("\"description\": \"HTTP response status code.\"\r\n");
            
            #line 88 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"

    }

            
            #line default
            #line hidden
            
            #line 91 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indent));
            
            #line default
            #line hidden
            
            #line 91 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indentDelta));
            
            #line default
            #line hidden
            this.Write("},\r\n");
            
            #line 92 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indent));
            
            #line default
            #line hidden
            
            #line 92 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indentDelta));
            
            #line default
            #line hidden
            this.Write("\"displayName\": \"");
            
            #line 92 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(otfrDef.Attr_Name));
            
            #line default
            #line hidden
            this.Write("\"\r\n");
            
            #line 93 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.DTDL\template\CommandDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(indent));
            
            #line default
            #line hidden
            this.Write("},\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public class CommandDefBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
